# Generated by Django 3.2.4 on 2021-06-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box_office_app', '0002_movie_release_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
