# Generated by Django 3.2.4 on 2021-06-21 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box_office_app', '0003_comment_movie_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='added_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='added_movies', to='box_office_app.user'),
            preserve_default=False,
        ),
    ]
